# Generated by Django 6.0.7 on 2026-07-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invitation',
            table='invitations',
        ),
    ]
