services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: equaliza
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Senha123
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/home/user/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    stdin_open: true
    tty: true