# Generated by Django 6.0.7 on 2026-10-08 18:24

import apps.families.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_alter_family_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='settlement_start',
            field=models.DateField(default=apps.families.utils.current_month_start, help_text='Primeiro dia do mês a partir do qual os acertos entre membros contam.', verbose_name='Início do acerto de contas'),
        ),
    ]
