# Generated by Django 6.0.7 on 2026-07-13 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        ('users', '0002_auto_20260713_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='families.family'),
        ),
    ]
