# Generated by Django 6.0.7 on 2026-07-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_current_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(choices=[('avatar-1', 'Avatar 1'), ('avatar-2', 'Avatar 2'), ('avatar-3', 'Avatar 3'), ('avatar-4', 'Avatar 4'), ('avatar-5', 'Avatar 5'), ('avatar-6', 'Avatar 6'), ('avatar-7', 'Avatar 7')], default='avatar-1', max_length=30),
        ),
    ]
