/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/current/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["current_partial_update"];
        trace?: never;
    };
    "/api/families/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["families_list"];
        put?: never;
        post: operations["families_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/families/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["families_retrieve"];
        put: operations["families_update"];
        post?: never;
        delete: operations["families_destroy"];
        options?: never;
        head?: never;
        patch: operations["families_partial_update"];
        trace?: never;
    };
    "/api/families/members/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["families_members_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/families/members/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["families_members_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/families/members/{id}/status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["families_members_status_partial_update"];
        trace?: never;
    };
    "/api/finances/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["finances_categories_list"];
        put?: never;
        post: operations["finances_categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finances/categories/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["finances_categories_retrieve"];
        put: operations["finances_categories_update"];
        post?: never;
        delete: operations["finances_categories_destroy"];
        options?: never;
        head?: never;
        patch: operations["finances_categories_partial_update"];
        trace?: never;
    };
    "/api/finances/expenses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["finances_expenses_list"];
        put?: never;
        post: operations["finances_expenses_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finances/expenses/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["finances_expenses_retrieve"];
        put: operations["finances_expenses_update"];
        post?: never;
        delete: operations["finances_expenses_destroy"];
        options?: never;
        head?: never;
        patch: operations["finances_expenses_partial_update"];
        trace?: never;
    };
    "/api/finances/income/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["finances_income_list"];
        put?: never;
        post: operations["finances_income_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finances/income/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["finances_income_retrieve"];
        put: operations["finances_income_update"];
        post?: never;
        delete: operations["finances_income_destroy"];
        options?: never;
        head?: never;
        patch: operations["finances_income_partial_update"];
        trace?: never;
    };
    "/api/finances/members/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Membros da família (inclusive quem consulta), para o filtro de despesas e receitas. */
        get: operations["finances_members_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finances/recurring/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["finances_recurring_list"];
        put?: never;
        post: operations["finances_recurring_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finances/recurring/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["finances_recurring_retrieve"];
        put: operations["finances_recurring_update"];
        post?: never;
        delete: operations["finances_recurring_destroy"];
        options?: never;
        head?: never;
        patch: operations["finances_recurring_partial_update"];
        trace?: never;
    };
    "/api/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Verificação de saúde para o orquestrador (Render/Docker): confirma que o banco responde. */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["invitations_list"];
        put?: never;
        post: operations["invitations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["invitations_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/{token}/accept/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Permite que um usuário já cadastrado entre em uma família pelo link. */
        post: operations["invitations_accept_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/{token}/validate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["invitations_validate_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Endpoint para obtenção de tokens JWT que utiliza email como credencial.
         *
         *     Estende a TokenObtainPairView padrão para:
         *     - Utilizar email em vez de username como credencial principal.
         *     - Retornar dados adicionais do usuário na resposta.
         *     - Fornecer mensagens de erro personalizadas
         *     Returns:
         *         dict: Contêm:
         *         - refresh (str): Token de refresh para obter novos tokens de acesso.
         *         - access (str): Token de acesso para requisições autenticadas.
         *         - user (dict): Informações básicas do usuário (id, username, email).
         */
        post: operations["login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retorna as informações do usuário autenticado. */
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/password-reset/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/password-reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["profile_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["profile_partial_update"];
        trace?: never;
    };
    "/api/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/dashboard/charts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reports_dashboard_charts_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/dashboard/insights/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reports_dashboard_insights_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/dashboard/summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reports_dashboard_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settlements/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Acertos de contas entre membros: saldo, pagamentos, histórico e estorno. */
        get: operations["settlements_list"];
        put?: never;
        /** @description Acertos de contas entre membros: saldo, pagamentos, histórico e estorno. */
        post: operations["settlements_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settlements/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Acertos de contas entre membros: saldo, pagamentos, histórico e estorno. */
        post: operations["settlements_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settlements/balance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Acertos de contas entre membros: saldo, pagamentos, histórico e estorno. */
        get: operations["settlements_balance_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptInvitationData: {
            family: components["schemas"]["InvitationFamily"];
        };
        AcceptInvitationResponse: {
            data: components["schemas"]["AcceptInvitationData"];
        };
        /**
         * @description * `avatar-1` - Avatar 1
         *     * `avatar-2` - Avatar 2
         *     * `avatar-3` - Avatar 3
         *     * `avatar-4` - Avatar 4
         *     * `avatar-5` - Avatar 5
         *     * `avatar-6` - Avatar 6
         *     * `avatar-7` - Avatar 7
         * @enum {string}
         */
        AvatarEnum: "avatar-1" | "avatar-2" | "avatar-3" | "avatar-4" | "avatar-5" | "avatar-6" | "avatar-7";
        Balance: {
            month: string;
            settlement_start: string;
            /** Format: decimal */
            my_balance: string;
            members: components["schemas"]["BalanceMember"][];
            suggestions: components["schemas"]["Suggestion"][];
        };
        BalanceMember: {
            id: number;
            name: string;
            is_active: boolean;
            /** Format: decimal */
            paid: string;
            /** Format: decimal */
            quota: string;
            /** Format: decimal */
            difference: string;
            /** Format: decimal */
            previous_balance: string;
            /** Format: decimal */
            settled: string;
            /** Format: decimal */
            balance: string;
        };
        CategoryComparison: {
            name: string;
            /** Format: double */
            value: number;
            /** Format: double */
            average: number | null;
            /** Format: double */
            change: number | null;
        };
        CreateExpenseRequest: {
            /** Format: decimal */
            amount: string;
            /** Format: date */
            date?: string;
            description?: string;
            category: number;
        };
        CreateFamilyRequest: {
            /** Nome */
            name: string;
        };
        CreateFinancialCategoryRequest: {
            name: string;
            type: components["schemas"]["TypeEnum"];
        };
        CreateIncomeRequest: {
            /** Format: decimal */
            amount: string;
            /** Format: date */
            date?: string;
            description?: string;
            category: number;
        };
        CreateInvitationRequest: {
            /** Format: email */
            email: string;
        };
        CreateRecurringTransactionRequest: {
            type: components["schemas"]["TypeEnum"];
            /** Format: decimal */
            amount: string;
            description?: string;
            category: number;
            frequency: components["schemas"]["FrequencyEnum"];
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date?: string | null;
        };
        CreateSettlementRequest: {
            /** @description Id do usuário que recebe. */
            receiver: number;
            /** Format: decimal */
            amount: string;
            /** @description Mês acertado, no formato AAAA-MM. */
            month: string;
            /** @default  */
            note: string;
            /**
             * Format: date
             * @description Data do pagamento; hoje por padrão.
             */
            paid_at?: string;
        };
        /** @description Serializador para obter um par de token e dados do usuário que usa email e senha para autenticação. */
        CustomTokenObtainPairRequest: {
            username?: string;
            email: string;
            password: string;
        };
        DashboardChart: {
            income_vs_expense: components["schemas"]["IncomeVsExpense"][];
            expenses_by_category: components["schemas"]["ExpensesByCategory"][];
            member_contributions: components["schemas"]["MemberContributions"][];
        };
        DashboardInsights: {
            insights: components["schemas"]["Insight"][];
            comparisons: components["schemas"]["CategoryComparison"][];
            has_expenses: boolean;
            has_history: boolean;
            has_previous: boolean;
            history_periods: number;
            average_label: string;
            above_count: number;
            below_count: number;
            dropped_count: number;
        };
        DashboardSummary: {
            /** Format: decimal */
            balance: string;
            /** Format: decimal */
            income: string;
            /** Format: decimal */
            expense: string;
            members: number;
        };
        /** @description Resposta simples com uma mensagem (`{"detail": "..."}`). */
        Detail: {
            detail: string;
        };
        ExpensesByCategory: {
            category: string;
            /** Format: double */
            value: number;
        };
        FamilyMemberStatus: {
            readonly id: number;
            is_active?: boolean;
        };
        /** @description Família vista pelo usuário logado: sua função e quantos membros ativos ela tem. */
        FamilyOverview: {
            readonly id: number;
            /** Nome */
            readonly name: string;
            readonly role: string | null;
            readonly is_active_member: boolean;
            readonly members_count: number;
            /** Format: date-time */
            readonly created_at: string | null;
            /** Format: date-time */
            readonly updated_at: string | null;
        };
        /**
         * @description * `WEEKLY` - Semanal
         *     * `MONTHLY` - Mensal
         *     * `YEARLY` - Anual
         * @enum {string}
         */
        FrequencyEnum: "WEEKLY" | "MONTHLY" | "YEARLY";
        Health: {
            status: string;
        };
        IncomeVsExpense: {
            period: string;
            /** Format: double */
            income: number;
            /** Format: double */
            expense: number;
        };
        Insight: {
            kind: string;
            tone: string;
            tag: string;
            title: string;
            body: string;
            bars: components["schemas"]["InsightBar"][];
            progress: components["schemas"]["InsightProgress"] | null;
            spark: components["schemas"]["InsightSparkPoint"][];
            note: string | null;
        };
        InsightBar: {
            label: string;
            value: string;
            /** Format: double */
            fraction: number;
            highlighted: boolean;
        };
        InsightProgress: {
            /** Format: double */
            fraction: number;
            start: string;
            end: string;
        };
        InsightSparkPoint: {
            label: string;
            value: string;
            /** Format: double */
            fraction: number;
            highlighted: boolean;
        };
        InvitationFamily: {
            id: number;
            name: string;
        };
        ListExpense: {
            readonly id: number;
            /** Format: decimal */
            amount: string;
            /** Format: date */
            date?: string;
            readonly category: components["schemas"]["ListFinancialCategory"];
            description?: string;
            readonly created_by: components["schemas"]["UserRef"] | null;
            /** Format: date-time */
            readonly created_at: string | null;
            /** Format: date-time */
            readonly updated_at: string | null;
        };
        ListFamily: {
            readonly id: number;
            /** Nome */
            readonly name: string;
            /** Format: date-time */
            readonly created_at: string | null;
            /** Format: date-time */
            readonly updated_at: string | null;
        };
        ListFamilyMember: {
            readonly id: number;
            readonly name: string;
            /** Format: email */
            email: string;
            readonly role: string;
            readonly avatar: string;
            /** Format: date-time */
            readonly joined_at: string;
            is_active?: boolean;
        };
        ListFinancialCategory: {
            readonly id: number;
            name: string;
            type: components["schemas"]["TypeEnum"];
            readonly is_default: boolean;
            readonly usage_count: number | null;
        };
        ListIncome: {
            readonly id: number;
            /** Format: decimal */
            amount: string;
            /** Format: date */
            date?: string;
            readonly category: components["schemas"]["ListFinancialCategory"];
            description?: string;
            readonly created_by: components["schemas"]["UserRef"] | null;
            /** Format: date-time */
            readonly created_at: string | null;
            /** Format: date-time */
            readonly updated_at: string | null;
        };
        ListInvitation: {
            readonly id: number;
            email?: (string) | null;
            /** Format: date-time */
            readonly created_at: string | null;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            accepted_at?: string | null;
            readonly status: string;
            readonly link: string;
        };
        ListRecurringTransaction: {
            readonly id: number;
            type: components["schemas"]["TypeEnum"];
            /** Format: decimal */
            amount: string;
            description?: string;
            readonly category: components["schemas"]["ListFinancialCategory"];
            frequency: components["schemas"]["FrequencyEnum"];
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date?: string | null;
            /** Format: date */
            next_date: string;
            is_active?: boolean;
            readonly created_by: components["schemas"]["UserRef"] | null;
            /** Format: date-time */
            readonly created_at: string | null;
            /** Format: date-time */
            readonly updated_at: string | null;
        };
        ListSettlement: {
            readonly id: number;
            readonly payer: components["schemas"]["UserRef"];
            readonly receiver: components["schemas"]["UserRef"];
            /** Format: decimal */
            amount: string;
            readonly reference_month: string;
            /** Format: date */
            paid_at?: string;
            note?: string;
            status?: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            cancelled_at?: string | null;
            readonly cancelled_by: components["schemas"]["UserRef"] | null;
            /** Format: decimal */
            remaining_after?: string;
            readonly carried_to: string | null;
        };
        MemberContributions: {
            member: string;
            /** Format: double */
            expected: number;
            /** Format: double */
            paid: number;
            /** Format: double */
            difference: number;
        };
        PaginatedFamilyOverviewList: components["schemas"]["FamilyOverview"][] | {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["FamilyOverview"][];
        };
        PaginatedListExpenseList: components["schemas"]["ListExpense"][] | {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ListExpense"][];
        };
        PaginatedListFamilyMemberList: components["schemas"]["ListFamilyMember"][] | {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ListFamilyMember"][];
        };
        PaginatedListFinancialCategoryList: components["schemas"]["ListFinancialCategory"][] | {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ListFinancialCategory"][];
        };
        PaginatedListIncomeList: components["schemas"]["ListIncome"][] | {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ListIncome"][];
        };
        PaginatedListInvitationList: components["schemas"]["ListInvitation"][] | {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ListInvitation"][];
        };
        PaginatedListRecurringTransactionList: components["schemas"]["ListRecurringTransaction"][] | {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ListRecurringTransaction"][];
        };
        PaginatedListSettlementList: components["schemas"]["ListSettlement"][] | {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ListSettlement"][];
        };
        PasswordResetConfirmRequest: {
            uid: string;
            token: string;
            password: string;
        };
        PasswordResetRequestRequest: {
            /** Format: email */
            email: string;
        };
        PatchedCurrentFamilyRequest: {
            family_id?: number;
        };
        PatchedFamilyMemberStatusRequest: {
            is_active?: boolean;
        };
        PatchedProfileRequest: {
            /** Primeiro nome */
            first_name?: string;
            /** Último nome */
            last_name?: string;
            avatar?: components["schemas"]["AvatarEnum"];
        };
        PatchedUpdateExpenseRequest: {
            /** Format: decimal */
            amount?: string;
            /** Format: date */
            date?: string;
            description?: string;
            category?: number;
        };
        PatchedUpdateFamilyRequest: {
            /** Nome */
            name?: string;
        };
        PatchedUpdateFinancialCategoryRequest: {
            name?: string;
            type?: components["schemas"]["TypeEnum"];
        };
        PatchedUpdateIncomeRequest: {
            /** Format: decimal */
            amount?: string;
            /** Format: date */
            date?: string;
            description?: string;
            category?: number;
        };
        PatchedUpdateRecurringTransactionRequest: {
            /** Format: decimal */
            amount?: string;
            description?: string;
            category?: number;
            /** Format: date */
            end_date?: string | null;
            is_active?: boolean;
        };
        Profile: {
            /** Primeiro nome */
            first_name?: string;
            /** Último nome */
            last_name?: string;
            avatar?: components["schemas"]["AvatarEnum"];
        };
        ProfileRequest: {
            /** Primeiro nome */
            first_name?: string;
            /** Último nome */
            last_name?: string;
            avatar?: components["schemas"]["AvatarEnum"];
        };
        RegisterRequest: {
            first_name: string;
            last_name: string;
            /** Format: email */
            email: string;
            password: string;
            family_name?: string;
            /** Format: uuid */
            token?: string;
        };
        RegisterResponse: {
            user: components["schemas"]["RegisteredUser"];
        };
        RegisteredUser: {
            id: number;
            /** Format: email */
            email: string;
            first_name: string;
            last_name: string;
        };
        /**
         * @description * `ACTIVE` - Ativo
         *     * `CANCELLED` - Estornado
         * @enum {string}
         */
        StatusEnum: "ACTIVE" | "CANCELLED";
        Suggestion: {
            payer: number;
            payer_name: string;
            receiver: number;
            receiver_name: string;
            /** Format: decimal */
            amount: string;
        };
        /**
         * @description * `EXPENSE` - Despesa
         *     * `INCOME` - Receita
         * @enum {string}
         */
        TypeEnum: "EXPENSE" | "INCOME";
        UpdateExpenseRequest: {
            /** Format: decimal */
            amount: string;
            /** Format: date */
            date?: string;
            description?: string;
            category: number;
        };
        UpdateFamilyRequest: {
            /** Nome */
            name: string;
        };
        UpdateFinancialCategoryRequest: {
            name: string;
            type: components["schemas"]["TypeEnum"];
        };
        UpdateIncomeRequest: {
            /** Format: decimal */
            amount: string;
            /** Format: date */
            date?: string;
            description?: string;
            category: number;
        };
        UpdateRecurringTransactionRequest: {
            /** Format: decimal */
            amount: string;
            description?: string;
            category: number;
            /** Format: date */
            end_date?: string | null;
            is_active?: boolean;
        };
        User: {
            readonly id: number;
            /**
             * E-mail
             * Format: email
             */
            email: string;
            /** Primeiro nome */
            first_name?: string;
            /** Último nome */
            last_name?: string;
            readonly current_family: components["schemas"]["ListFamily"];
            readonly families: components["schemas"]["ListFamily"][];
            readonly role: string | null;
            readonly avatar: components["schemas"]["UserAvatar"];
        };
        UserAvatar: {
            id: string;
            url: string;
        };
        /** @description Referência resumida a um usuário (quem criou um registro). */
        UserRef: {
            id: number;
            name: string;
        };
        ValidateInvitationData: {
            /** Format: email */
            email: string;
            family: components["schemas"]["InvitationFamily"];
            /** Format: date-time */
            expires_at: string;
        };
        ValidateInvitationResponse: {
            data: components["schemas"]["ValidateInvitationData"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    current_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCurrentFamilyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCurrentFamilyRequest"];
                "multipart/form-data": components["schemas"]["PatchedCurrentFamilyRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    families_list: {
        parameters: {
            query?: {
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a serem retornados por página. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFamilyOverviewList"];
                };
            };
        };
    };
    families_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFamilyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CreateFamilyRequest"];
                "multipart/form-data": components["schemas"]["CreateFamilyRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListFamily"];
                };
            };
        };
    };
    families_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este family. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListFamily"];
                };
            };
        };
    };
    families_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este family. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFamilyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UpdateFamilyRequest"];
                "multipart/form-data": components["schemas"]["UpdateFamilyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListFamily"];
                };
            };
        };
    };
    families_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este family. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    families_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este family. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUpdateFamilyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUpdateFamilyRequest"];
                "multipart/form-data": components["schemas"]["PatchedUpdateFamilyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListFamily"];
                };
            };
        };
    };
    families_members_list: {
        parameters: {
            query?: {
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a serem retornados por página. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListFamilyMemberList"];
                };
            };
        };
    };
    families_members_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este family member. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    families_members_status_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este family member. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedFamilyMemberStatusRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedFamilyMemberStatusRequest"];
                "multipart/form-data": components["schemas"]["PatchedFamilyMemberStatusRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyMemberStatus"];
                };
            };
        };
    };
    finances_categories_list: {
        parameters: {
            query?: {
                name?: string;
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a serem retornados por página. */
                page_size?: number;
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListFinancialCategoryList"];
                };
            };
        };
    };
    finances_categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFinancialCategoryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CreateFinancialCategoryRequest"];
                "multipart/form-data": components["schemas"]["CreateFinancialCategoryRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListFinancialCategory"];
                };
            };
        };
    };
    finances_categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este financial category. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListFinancialCategory"];
                };
            };
        };
    };
    finances_categories_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este financial category. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFinancialCategoryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UpdateFinancialCategoryRequest"];
                "multipart/form-data": components["schemas"]["UpdateFinancialCategoryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListFinancialCategory"];
                };
            };
        };
    };
    finances_categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este financial category. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finances_categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este financial category. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUpdateFinancialCategoryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUpdateFinancialCategoryRequest"];
                "multipart/form-data": components["schemas"]["PatchedUpdateFinancialCategoryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListFinancialCategory"];
                };
            };
        };
    };
    finances_expenses_list: {
        parameters: {
            query?: {
                categories?: number[];
                from_date?: string;
                members?: number[];
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a serem retornados por página. */
                page_size?: number;
                to_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListExpenseList"];
                };
            };
        };
    };
    finances_expenses_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExpenseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CreateExpenseRequest"];
                "multipart/form-data": components["schemas"]["CreateExpenseRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListExpense"];
                };
            };
        };
    };
    finances_expenses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este expense. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListExpense"];
                };
            };
        };
    };
    finances_expenses_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este expense. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExpenseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UpdateExpenseRequest"];
                "multipart/form-data": components["schemas"]["UpdateExpenseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListExpense"];
                };
            };
        };
    };
    finances_expenses_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este expense. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finances_expenses_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este expense. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUpdateExpenseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUpdateExpenseRequest"];
                "multipart/form-data": components["schemas"]["PatchedUpdateExpenseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListExpense"];
                };
            };
        };
    };
    finances_income_list: {
        parameters: {
            query?: {
                categories?: number[];
                from_date?: string;
                members?: number[];
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a serem retornados por página. */
                page_size?: number;
                to_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListIncomeList"];
                };
            };
        };
    };
    finances_income_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIncomeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CreateIncomeRequest"];
                "multipart/form-data": components["schemas"]["CreateIncomeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListIncome"];
                };
            };
        };
    };
    finances_income_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este income. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListIncome"];
                };
            };
        };
    };
    finances_income_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este income. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIncomeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UpdateIncomeRequest"];
                "multipart/form-data": components["schemas"]["UpdateIncomeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListIncome"];
                };
            };
        };
    };
    finances_income_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este income. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finances_income_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este income. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUpdateIncomeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUpdateIncomeRequest"];
                "multipart/form-data": components["schemas"]["PatchedUpdateIncomeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListIncome"];
                };
            };
        };
    };
    finances_members_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRef"][];
                };
            };
        };
    };
    finances_recurring_list: {
        parameters: {
            query?: {
                /**
                 * @description * `WEEKLY` - Semanal
                 *     * `MONTHLY` - Mensal
                 *     * `YEARLY` - Anual
                 */
                frequency?: "MONTHLY" | "WEEKLY" | "YEARLY";
                is_active?: boolean;
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a serem retornados por página. */
                page_size?: number;
                /**
                 * @description * `EXPENSE` - Despesa
                 *     * `INCOME` - Receita
                 */
                type?: "EXPENSE" | "INCOME";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListRecurringTransactionList"];
                };
            };
        };
    };
    finances_recurring_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecurringTransactionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CreateRecurringTransactionRequest"];
                "multipart/form-data": components["schemas"]["CreateRecurringTransactionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRecurringTransaction"];
                };
            };
        };
    };
    finances_recurring_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este recurring transaction. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRecurringTransaction"];
                };
            };
        };
    };
    finances_recurring_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este recurring transaction. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecurringTransactionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UpdateRecurringTransactionRequest"];
                "multipart/form-data": components["schemas"]["UpdateRecurringTransactionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRecurringTransaction"];
                };
            };
        };
    };
    finances_recurring_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este recurring transaction. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finances_recurring_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este recurring transaction. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUpdateRecurringTransactionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUpdateRecurringTransactionRequest"];
                "multipart/form-data": components["schemas"]["PatchedUpdateRecurringTransactionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRecurringTransaction"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    invitations_list: {
        parameters: {
            query?: {
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a serem retornados por página. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListInvitationList"];
                };
            };
        };
    };
    invitations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CreateInvitationRequest"];
                "multipart/form-data": components["schemas"]["CreateInvitationRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListInvitation"];
                };
            };
        };
    };
    invitations_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este invitation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    invitations_accept_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptInvitationResponse"];
                };
            };
        };
    };
    invitations_validate_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateInvitationResponse"];
                };
            };
        };
    };
    login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomTokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomTokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["CustomTokenObtainPairRequest"];
            };
        };
        responses: {
            /** @description Sessão iniciada. Os tokens seguem em cookies HttpOnly, sem corpo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            205: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetRequestRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirmRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    profile_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProfileRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProfileRequest"];
                "multipart/form-data": components["schemas"]["ProfileRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    profile_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProfileRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProfileRequest"];
                "multipart/form-data": components["schemas"]["PatchedProfileRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
        };
    };
    reports_dashboard_charts_retrieve: {
        parameters: {
            query?: {
                categories?: number[];
                from_date?: string;
                to_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardChart"];
                };
            };
        };
    };
    reports_dashboard_insights_retrieve: {
        parameters: {
            query: {
                categories?: number[];
                from_date: string;
                /**
                 * @description * `DAY` - DAY
                 *     * `WEEK` - WEEK
                 *     * `MONTH` - MONTH
                 *     * `YEAR` - YEAR
                 *     * `PERIOD` - PERIOD
                 */
                period_type?: "DAY" | "WEEK" | "MONTH" | "YEAR" | "PERIOD";
                to_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardInsights"];
                };
            };
        };
    };
    reports_dashboard_summary_retrieve: {
        parameters: {
            query?: {
                categories?: number[];
                from_date?: string;
                to_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
    settlements_list: {
        parameters: {
            query?: {
                /** @description Filtra por quem pagou ou recebeu. */
                member?: number;
                month?: string;
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a serem retornados por página. */
                page_size?: number;
                /**
                 * @description * `ACTIVE` - Ativo
                 *     * `CANCELLED` - Estornado
                 */
                status?: "ACTIVE" | "CANCELLED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListSettlementList"];
                };
            };
        };
    };
    settlements_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSettlementRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CreateSettlementRequest"];
                "multipart/form-data": components["schemas"]["CreateSettlementRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSettlement"];
                };
            };
        };
    };
    settlements_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este settlement. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSettlement"];
                };
            };
        };
    };
    settlements_balance_retrieve: {
        parameters: {
            query?: {
                /** @description Mês no formato AAAA-MM. Sem ele, vale o mês atual. */
                month?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Balance"];
                };
            };
        };
    };
}
