# Generated by Django 6.0.7 on 2026-07-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expense',
            table='expenses',
        ),
        migrations.AlterModelTable(
            name='income',
            table='incomes',
        ),
    ]
