# Generated by Django 6.0.7 on 2026-07-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_expense_table_alter_income_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='financialcategory',
            table='categories',
        ),
    ]
