# Generated by Django 6.0.7 on 2026-07-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        ('finance', '0004_create_default_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='financialcategory',
            constraint=models.UniqueConstraint(fields=('family', 'type', 'name'), name='unique_financial_category_per_family'),
        ),
    ]
