# Generated by Django 5.2.4 on 2026-07-31 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0002_alter_family_created_by"),
        ("finance", "0004_create_default_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="finance.financialcategory",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="income",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="finance.financialcategory",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddConstraint(
            model_name="financialcategory",
            constraint=models.UniqueConstraint(
                fields=("family", "type", "name"),
                name="unique_financial_category_per_family",
            ),
        ),
    ]
