# Generated by Django 6.0.7 on 2026-10-06 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_alter_family_created_by'),
        ('finance', '0006_recurringtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['family', '-date'], name='exp_family_date_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['family', '-date'], name='inc_family_date_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['family', 'is_active', 'next_date'], name='rec_family_active_next_idx'),
        ),
    ]
