# Generated by Django 6.0.7 on 2026-10-08 18:24

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0003_family_settlement_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='created_at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='updated_at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_month', models.DateField(help_text='Primeiro dia do mês acertado.')),
                ('paid_at', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('CANCELLED', 'Estornado')], default='ACTIVE', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('remaining_after', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('carried_to', models.DateField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='families.family')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_paid', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_received', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settlements',
                'indexes': [models.Index(fields=['family', 'reference_month'], name='settle_family_month_idx'), models.Index(fields=['family', '-paid_at'], name='settle_family_paid_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('payer', models.F('receiver')), _negated=True), name='settlement_payer_not_receiver'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='settlement_amount_positive')],
            },
        ),
    ]
